Fix Time locals in airb REPL
The `airb` REPL calls `#inspect` on each value returned by
`Artichoke::eval`. `Time` raises `NotImplementedError` in its `#inspect`
implementation. There is a nasty interaction here between the
`Time#inspect` implementation and the mruby locals tables that cause a
local bound to a `Time` to get reassigned to the `NotImplementedError`.

```console
artichoke 0.1.0-pre.0 (2020-10-01 revision 3626) [x86_64-apple-darwin]
[rustc 1.46.0 (04488afe3 2020-08-24)]
>>> t = Time.now
=>
>>> t.month
Traceback (most recent call last):
	1: from (airb):2
NoMethodError (undefined method 'month')
>>> t.class
=> NilClass
>>>
```

With this patch, the REPL behaves like this:

```console
artichoke 0.1.0-pre.0 (2020-10-01 revision 3627) [x86_64-apple-darwin]
[rustc 1.46.0 (04488afe3 2020-08-24)]
>>> t = Time.now
=> Time<Time#inspect is not implemented>
>>> t.month
=> 9
```