Improve error messages in artichoke-backend and spec-runner functional tests
Modify functional tests to panic on exception such that backtraces have
one frame per line of panic message.

Modify functional tests so that errors eval'ing the functional test
source (and e.g. requiring packages from stdlib) print the same
prettified exception message and backtrace.

These panics look like this:

```console
$ cargo test -q -p artichoke-backend array::tests::functional

running 1 test
F
failures:

---- extn::core::array::tests::functional stdout ----
thread 'extn::core::array::tests::functional' panicked at '
Array tests failed with RuntimeError exception
    message: ""
    backtrace:
        (eval):43:in inline_get
        (eval):5:in spec
        (eval):1
', artichoke-backend/src/extn/core/array/mod.rs:352:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

failures:
    extn::core::array::tests::functional

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 227 filtered out; finished in 0.05s

error: test failed, to rerun pass '-p artichoke-backend --lib'
```

This commit was extracted from #1222.